In [ ]:
#like AoC_2015
#but uses OOP

In [1]:
import numpy as np
import itertools
import warnings
warnings.simplefilter(action='ignore')

In [2]:
bosshp = 104
bossdamage = 8
bossarmor = 1

playerhp = 100
playerdamage = 0
playerarmor = 0


In [3]:
from collections import namedtuple
Item = namedtuple('item', ['name', 'cost', 'damage', 'armor'])

weaponsnt = [
    Item('Dagger', 8, 4, 0),
    Item('Shortsword', 10, 5, 0),
    Item('Warhammer', 25, 6, 0),
    Item('Longsword', 40, 7, 0),
    Item('Greataxe', 74, 8, 0),
]

armornt = [
    Item('Leather', 13, 0, 1),
    Item('Chainmail', 31, 0, 2),
    Item('Splintmail', 53, 0, 3),
    Item('Bandedmail', 75, 0, 4),
    Item('Platemail', 102, 0, 5),
    Item('Naked', 0, 0, 0),
]

ringsnt = [
    Item('Damage +1', 25, 1, 0),
    Item('Damage +2', 50, 2, 0),
    Item('Damage +3', 100, 3, 0),
    Item('Defense +1', 20, 0, 1),
    Item('Defense +2', 40, 0, 2),
    Item('Defense +3', 80, 0, 3),
]

In [4]:
# class Boss:
#     def __init__(self, hp, damage, armor):
#         self.hp = hp
#         self.damage = damage
#         self.armor = armor
        
#     def calc_actdamage(self, playerarmor):
#         self.actdamage = self.damage - playerarmor
#         if (self.actdamage < 1):
#             self.actdamage = 1
        
# class Player:
#     def __init__(self, spent, hp, damage, armor):
#         self.spent = spent
#         self.hp = hp
#         self.damage = damage
#         self.armor = armor
    
#     def calc_actdamage(self, bossarmor):
#         self.actdamage = self.damage - bossarmor
#         if (self.actdamage < 1):
#             self.actdamage = 1

In [5]:
class RpgChara:
    def __init__(self, hp, damage, armor):
        self.hp = hp
        self.damage = damage
        self.armor = armor
        
    def calc_actdamage(self, enemyarmor):
        self.actdamage = self.damage - enemyarmor
        if (self.actdamage < 1):
            self.actdamage = 1
            
class Boss(RpgChara):
    pass
    
class Player(RpgChara):
    def __init__(self, spent, hp, damage, armor):
        super().__init__(hp, damage, armor)
        self.spent = spent


In [10]:
class Foo:
    bar = 1
    def __init__(self, baz):
        self.baz = baz

a = Foo(9)
b = Foo(6)

print(a.bar)
Foo.bar = 99999
print(Foo.bar)
print(a.bar)
print(b.bar)
b.bar = 'asdf'
print(b.bar)

1
99999
99999
99999
asdf


In [6]:
wn = 5 #weapons
an = 6 #armor
rn = 22 #rings

comb = wn * an * rn #total number of possibilities

#setup arrays
player_spent = np.full((wn, an, rn), np.nan)
player_damage = np.full((wn, an, rn), np.nan) #damage
player_armor = np.full((wn, an, rn), np.nan) #cost

#setup arrays
weapons = np.full((wn, 3), 0)
armor = np.full((an, 3), 0)
rings0 = np.full((6, 3), 0)
rings = np.full((rn, 3), 0)

weapons[:,:] = [[8, 4, 0], [10, 5, 0], [25, 6, 0], [40, 7, 0], [74, 8, 0]]
armor[:,:] = [[13, 0, 1], [31, 0, 2], [53, 0, 3], [75, 0, 4], [102, 0, 5], [0, 0, 0]]
rings0[:,:] = [[25, 1, 0], [50, 2, 0], [100, 3, 0], [20, 0, 1], [40, 0, 2], [80, 0, 3]]

ring_combs = (list(itertools.combinations('012345', 2)))
print(ring_combs)

[('0', '1'), ('0', '2'), ('0', '3'), ('0', '4'), ('0', '5'), ('1', '2'), ('1', '3'), ('1', '4'), ('1', '5'), ('2', '3'), ('2', '4'), ('2', '5'), ('3', '4'), ('3', '5'), ('4', '5')]


# The 22 ring combinations

In [7]:
for i in range(0, len(ring_combs)):
    rings[i, 0] = int(rings0[ring_combs[i][0]][0] + rings0[ring_combs[i][1]][0]) #cost
    rings[i, 1] = int(rings0[ring_combs[i][0]][1] + rings0[ring_combs[i][1]][1]) #damage
    rings[i, 2] = int(rings0[ring_combs[i][0]][2] + rings0[ring_combs[i][1]][2]) #armor
rings[15:-1, :] = rings0[:,:]

print(rings)

[[  75.    3.    0.]
 [ 125.    4.    0.]
 [  45.    1.    1.]
 [  65.    1.    2.]
 [ 105.    1.    3.]
 [ 150.    5.    0.]
 [  70.    2.    1.]
 [  90.    2.    2.]
 [ 130.    2.    3.]
 [ 120.    3.    1.]
 [ 140.    3.    2.]
 [ 180.    3.    3.]
 [  60.    0.    3.]
 [ 100.    0.    4.]
 [ 120.    0.    5.]
 [  25.    1.    0.]
 [  50.    2.    0.]
 [ 100.    3.    0.]
 [  20.    0.    1.]
 [  40.    0.    2.]
 [  80.    0.    3.]
 [   0.    0.    0.]]


In [8]:
for w in range(0, wn):
    for a in range(0, an):
        for r in range(0, rn):
            player_spent[w, a, r] = weapons[w, 0] + armor[a, 0] + rings[r, 0]
            player_damage[w, a, r] = weapons[w, 1] + armor[a, 1] + rings[r, 1]
            player_armor[w, a, r] = weapons[w, 2] + armor[a, 2] + rings[r, 2]

In [9]:
print(weapons)
print('-')
print(armor)

[[  8.   4.   0.]
 [ 10.   5.   0.]
 [ 25.   6.   0.]
 [ 40.   7.   0.]
 [ 74.   8.   0.]]
-
[[  13.    0.    1.]
 [  31.    0.    2.]
 [  53.    0.    3.]
 [  75.    0.    4.]
 [ 102.    0.    5.]
 [   0.    0.    0.]]


In [10]:
-

lowest spend while still winning = 91.0
item(name='Longsword', cost=40, damage=7, armor=0)
item(name='Chainmail', cost=31, damage=0, armor=2)
ringscombi [ 20.   0.   1.]
18
-
highest spend while still losing = 158.0
item(name='Dagger', cost=8, damage=4, armor=0)
item(name='Naked', cost=0, damage=0, armor=0)
ringscombi [ 150.    5.    0.]
5
-
win_no= 525
lose_no= 135
