In [ ]:
#like AoC_2015
#but tries to use namedtuple (but fails as it gets too complicated)
#but uses OOP

In [1]:
try:
    from IPython import get_ipython
    get_ipython().magic('reset -f')  
except:
    pass
from IPython import get_ipython
ipython = get_ipython().magic
import os
os.chdir('/Users/markprosser/Desktop/PythonScripts')
import MCP_functions as MCP
import numpy as np
import matplotlib.pyplot as plt
import sys
import random
plt.close("all")
import itertools
import warnings
warnings.simplefilter(action='ignore')

from collections import namedtuple
Item = namedtuple('item', ['name', 'cost', 'damage', 'armor'])

In [2]:
class Boss:
    def __init__(self, hp, damage, armor):
        self.hp = hp
        self.damage = damage
        self.armor = armor
        
class Player:
    def __init__(self, spent, hp, damage, armor):
        self.spent = spent
        self.hp = hp
        self.damage = damage
        self.armor = armor

In [65]:
type(rings0)

list

In [70]:
wn = 5 #weapons
an = 6 #armor
rn = 22 #rings

comb = wn * an * rn #total number of possibilities

my_cost = np.full((wn, an, rn), np.nan)
my_damage = np.full((wn, an, rn), np.nan) #damage
my_armor = np.full((wn, an, rn), np.nan) #cost

weapons = np.full((wn, 3), 0)
armor = np.full((an, 3), 0)
rings0 = np.full((6, 3), 0)
rings = np.full((rn, 3), 0)

weaponsnt = [
    Item('Dagger', 8, 4, 0),
    Item('Shortsword', 10, 5, 0),
    Item('Warhammer', 25, 6, 0),
    Item('Longsword', 40, 7, 0),
    Item('Greataxe', 74, 8, 0),
]

armornt = [
    Item('Leather', 13, 0, 1),
    Item('Chainmail', 31, 0, 2),
    Item('Splintmail', 53, 0, 3),
    Item('Bandedmail', 75, 0, 4),
    Item('Platemail', 102, 0, 5),
    Item('Naked', 0, 0, 0),
]

ringsnt = [
    Item('Damage +1', 25, 1, 0),
    Item('Damage +2', 50, 2, 0),
    Item('Damage +3', 100, 3, 0),
    Item('Defense +1', 20, 0, 1),
    Item('Defense +2', 40, 0, 2),
    Item('Defense +3', 80, 0, 3),
]


# weapons[:,:] = [[8, 4, 0], [10, 5, 0], [25, 6, 0], [40, 7, 0], [74, 8, 0]]
# armor[:,:] = [[13, 0, 1], [31, 0, 2], [53, 0, 3], [75, 0, 4], [102, 0, 5], [0, 0, 0]]
# rings0[:,:] = [[25, 1, 0], [50, 2, 0], [100, 3, 0], [20, 0, 1], [40, 0, 2], [80, 0, 3]]

ring_combs = (list(itertools.combinations('012345', 2)))
print(ring_combs)


rings = np.full((rn, 3), 0)

[('0', '1'), ('0', '2'), ('0', '3'), ('0', '4'), ('0', '5'), ('1', '2'), ('1', '3'), ('1', '4'), ('1', '5'), ('2', '3'), ('2', '4'), ('2', '5'), ('3', '4'), ('3', '5'), ('4', '5')]


# The 22 ring combinations

In [73]:
for i in range(0, len(ring_combs)):
    rings[i, 0] = int(rings0[int(ring_combs[i][0])][1] + rings0[int(ring_combs[i][1])][1]) #cost
    rings[i, 1] = int(rings0[int(ring_combs[i][0])][2] + rings0[int(ring_combs[i][1])][2]) #damage
    rings[i, 2] = int(rings0[int(ring_combs[i][0])][3] + rings0[int(ring_combs[i][1])][3]) #armor
for i in range(0, len(rings0)):
    rings[15+i] = list(rings0[i][1:])

print(rings)

[[  75.    3.    0.]
 [ 125.    4.    0.]
 [  45.    1.    1.]
 [  65.    1.    2.]
 [ 105.    1.    3.]
 [ 150.    5.    0.]
 [  70.    2.    1.]
 [  90.    2.    2.]
 [ 130.    2.    3.]
 [ 120.    3.    1.]
 [ 140.    3.    2.]
 [ 180.    3.    3.]
 [  60.    0.    3.]
 [ 100.    0.    4.]
 [ 120.    0.    5.]
 [  25.    1.    0.]
 [  50.    2.    0.]
 [ 100.    3.    0.]
 [  20.    0.    1.]
 [  40.    0.    2.]
 [  80.    0.    3.]
 [   0.    0.    0.]]


In [74]:
for w in range(0, wn):
    for a in range(0, an):
        for r in range(0, rn):
            my_cost[w, a, r] = weapons[w][1] + armor[a][1] + rings[r][0]
            my_damage[w, a, r] = weapons[w][2] + armor[a][2] + rings[r][1]
            my_armor[w, a, r] = weapons[w][3] + armor[a][3] + rings[r][2]

In [64]:
print(weapons)
print('-')
print(armor)

[item(name='Dagger', cost=8, damage=4, armor=0), item(name='Shortsword', cost=10, damage=5, armor=0), item(name='Warhammer', cost=25, damage=6, armor=0), item(name='Longsword', cost=40, damage=7, armor=0), item(name='Greataxe', cost=74, damage=8, armor=0)]
-
[item(name='Leather', cost=13, damage=0, armor=1), item(name='Chainmail', cost=31, damage=0, armor=2), item(name='Splintmail', cost=53, damage=0, armor=3), item(name='Bandedmail', cost=75, damage=0, armor=4), item(name='Platemail', cost=102, damage=0, armor=5), item(name='Naked', cost=0, damage=0, armor=0)]
